apiVersion: v1
kind: Service
metadata:
  name: myapp
  labels:
    app: myapp
spec:
  type: NodePort
  ports:
    - port: 80
      name: http
      targetPort: 80
  selector:
    app: myapp
    version: v1
