apiVersion: v1
kind: Secret
metadata:
  name: github-auth
  annotations:
    tekton.dev/git-0: https://github.com  # Replace with the desired domain name.
type: kubernetes.io/basic-auth
stringData:
  username: $(username)
  password: $(password)  # Access token should be provided here, if 2 factor authentication is enabled.
