apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURBVENDQWVtZ0F3SUJBZ0lKQU9sbG5PNDZnQkN3TUEwR0NTcUdTSWIzRFFFQkN3VUFNQmN4RlRBVEJnTlYKQkFNTURERXdMakUxTWk0eE9ETXVNVEFlRncweU1EQTRNVGt5TURNNU5USmFGdzB6TURBNE1UY3lNRE01TlRKYQpNQmN4RlRBVEJnTlZCQU1NRERFd0xqRTFNaTR4T0RNdU1UQ0NBU0l3RFFZSktvWklodmNOQVFFQkJRQURnZ0VQCkFEQ0NBUW9DZ2dFQkFPR0dqY0tYK2NoVlZBejNWSi9KMUprc213UDNBUlRieHZBeFhUT01uOHEvbFNGWWNVbzgKUEpiKzBBRUNhcldPUTZEMUt2d2tWb01MMWhFaUJIUVZRNHd1bDlwb2IxLzgxOXlHeExaNER5d0NhU00xZGQ5MApqYU9nKzJKbnVEOUtvaE1TbkxDUW1BU3pKNjI1d0w0Mys3M0lxek96d3BBT1dJbGNmR0FMczVBSmZoSmRjTmo3CkZFUmdoNzB2c0VyZWorZVlYZmErb3dhOHNOZDg4MXRpeElVU20zVlVBanRxTy8xbWZkM3hlbkRCdXFPcThScjkKUW1Pb1NCNEpTVHhzVlg2Z1M1bEQwbEQ3cFVNVVFPcmtQUWs0c1plUmp6R1RrbEVndXNyby9IUnVXQ2trMFYxaQpvL3hmbU9DdXVEZ0xpdThQVHZRVWhlM2E0S3dLMWNIV0x5OENBd0VBQWFOUU1FNHdIUVlEVlIwT0JCWUVGQ1RTClAzS0UzNVNkSGRBWDY4Z2plNEQ5UEJUb01COEdBMVVkSXdRWU1CYUFGQ1RTUDNLRTM1U2RIZEFYNjhnamU0RDkKUEJUb01Bd0dBMVVkRXdRRk1BTUJBZjh3RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQUtyREI2VDZCTlJXTkV6YgpmWDVzMkF1V2FCVjRGTmE2cFBXMEhPQU03QlBDbWRxVW93UlkyN3BqamJSSHplZE1mbHhpcW1MWHhHblFXaDBPCkJGYWtkMUVVZ1MzZk1sUk1aMXFHTHhNdzZncHhrYzc4NmdZd2UvTzZvOUtCckRFK3hxZ1Z1YVlZeUloUWJwc3AKMEdqOUMzZTR4b1BmMVBud3Bua3Iwd0Q4RjRla3p5TEpuMjJqeVJFY1l4RjdvaDdlTWVVcjJ5WTkxaHdBNUFBbQpsNjFUczlFcVU1Q2J2a3pZUGpQR1RkMVk5NTBGQURnSUNyOWVTYnRGbkRVZTBxVDdWZFp5OHpCRkJnQkFJU283CkRxRXJRb1I2VWtuMFB1aTk5TmdKWGhnTVd0WVR5TXd3ZnJvZVhTSlJNdEsvclhTOTVBTEFEbnNHUkZvOG1tTGUKdmtqYmcyYz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    server: https://192.168.1.55:16443
  name: microk8s-cluster
contexts:
- context:
    cluster: microk8s-cluster
    user: admin
  name: microk8s
current-context: microk8s
kind: Config
preferences: {}
users:
- name: admin
  user:
    token: ZG0rVnhUME4vTDlmRUprQVFoQmIwZm5GUWFta3IvWHRob0s3Qk51cU9Paz0K
