apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-v2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
      version: v2
  template:
    metadata:
      labels:
        app: "myapp"
        version: "v2"
    spec:
      containers:
        - name: myapp
          image: janakiramm/myapp:v2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              name: http
