apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: standardized-docker-pipeline-example-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  storageClassName: nfs-provisioner
