---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: pr-create-namespace
spec:
  pipelineRef:
    name: p-run-kubectl-command
  workspaces:
  - name: shared-data
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
        storageClassName: nfs-provisioner
  params:
  - name: repo-url
    value: <gerrit-url>
  - name: branch-name
    value: <gerrit-branch-name>
  - name: set-namespace
    value: <namespace>
  - name: httpProxy
    value: "http://pxyapp.proxy.att.com:8080/"
  - name: httpsProxy
    value: "http://pxyapp.proxy.att.com:8080/"
  - name: noProxy
    value: "127.0.0.1,localhost,.att.com,10.96.0.0/12,.svc.cluster.local,32.68.220.18,.tekton-pipelines.svc,192.168.0.0/16"
  - name: kubectlCommand
    value: "kubectl create ns $(params.set-namespace)"
...
