---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: p-create-scdi
spec:
  workspaces:
  - name: shared-workspace
  tasks:
  - name: fetch-repository
    taskRef:
      kind: ClusterTask
      name: git-clone
    workspaces:
    - name: output
      workspace: shared-workspace
    params:
    - name: url
      value: https://github.com/slfletch/mvp
    - name: subdirectory
      value: ""
    - name: deleteExisting
      value: "true"
    - name: httpProxy
      value: "http://pxyapp.proxy.att.com:8080/"
    - name: httpsProxy
      value: "http://pxyapp.proxy.att.com:8080/"
    - name: noProxy
      value: "127.0.0.1,localhost,.att.com,10.96.0.0/12,.svc.cluster.local,32.68.220.18,.tekton-pipelines.svc,192.168.0.0/16"
  - name: docker-build
    taskRef:
      kind: ClusterTask
      name: docker-build
    runAfter:
    - fetch-repository
    workspaces:
    - name: source
      workspace: shared-workspace
    params:
    - name: image
      value: mtn52r08c001.mini.mtn52c.cci.att.com:30003/tenent0/scdi:1.1
    - name: dockerfile
      value: ./tenant1/Dockerfile
    - name: insecure_registry
      value: "mtn52r08c001.mini.mtn52c.cci.att.com:30003"
...
