---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: p-create-scdi
spec:
  workspaces:
  - name: shared-workspace
  params:
  - name: git-url
  - name: subdirectory
  - name: git-revision
  - name: deleteExisting
  - name: httpProxy
  - name: httpsProxy
  - name: noProxy
  - name: image
  - name: dockerfile
  - name: insecure_registry
  tasks:
  - name: fetch-repository
    taskRef:
      kind: ClusterTask
      name: git-clone
    workspaces:
    - name: output
      workspace: shared-workspace
    params:
    - name: url
      value: $(params.git-url)
    - name: subdirectory
      value: $(params.subdirectory)
    - name: deleteExisting
      value: $(params.deleteExisting)
    - name: httpProxy
      value: $(params.httpProxy)
    - name: httpsProxy
      value: $(params.httpsProxy)
    - name: noProxy
      value: $(params.noProxy)
  - name: docker-build
    taskRef:
      kind: ClusterTask
      name: docker-build
    runAfter:
    - fetch-repository
    workspaces:
    - name: source
      workspace: shared-workspace
    params:
    - name: image
      value: $(params.image)
    - name: build_extra_args
      value: "--build-arg HTTP_PROXY=$(params.httpProxy) --build-arg HTTPS_PROXY=$(params.httpsProxy) --build-arg NO_PROXY=$(params.noProxy)"
    - name: dockerfile
      value: $(params.dockerfile)
    - name: insecure_registry
      value: $(params.insecure_registry)
...
