---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: p-create-scdi
spec:
  workspaces:
  - name: shared-workspace
  params:
  - name: git-url
  - name: subdirectory
  - name: git-revision
  - name: deleteExisting
  - name: image
  - name: dockerfile
  - name: insecure_registry
  - name: context
  tasks:
  - name: fetch-repository
    taskRef:
      kind: ClusterTask
      name: git-clone
    workspaces:
    - name: output
      workspace: shared-workspace
    params:
    - name: revision
      value: $(params.git-revision)
    - name: url
      value: $(params.git-url)
    - name: subdirectory
      value: $(params.subdirectory)
    - name: deleteExisting
      value: $(params.deleteExisting)
  - name: docker-build
    taskRef:
      kind: ClusterTask
      name: docker-build
    runAfter:
    - fetch-repository
    workspaces:
    - name: source
      workspace: shared-workspace
    params:
    - name: image
      value: $(params.image)
    - name: build_extra_args
      value: ""
    - name: dockerfile
      value: $(params.dockerfile)
    - name: insecure_registry
      value: $(params.insecure_registry)
    - name: context
      value: $(params.context)
  - name: cicd
    taskRef:
      kind: ClusterTask
      name: cicd
    runAfter:
    - docker-build
    workspaces:
    - name: source
      workspace: shared-workspace
    params:
    - name: image
      value: $(params.image)
    - name: build_extra_args
      value: ""
    - name: dockerfile
      value: $(params.dockerfile)
    - name: insecure_registry
      value: $(params.insecure_registry)
    - name: context
      value: $(params.context)
...
