kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: task-admin
rules:
- apiGroups: ["tekton.dev"] # "" indicates the core API group
  resources: ["tasks"]
  verbs: ["get","patch","create", "apply", "describe","delete"]
- apiGroups: ["system:serviceaccounts","system:serviceaccounts:default","system:authenticated"] # "" indicates the core API group
  resources: ["serviceaccounts"]
  verbs: ["get","patch","create", "apply", "describe","delete"]
- apiGroups: ["*"] # "" indicates the core API group
  resources: ["*"]
  verbs: ["get","patch","create", "apply", "describe","delete"]
...
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: task-reader
rules:
- apiGroups: ["tekton.dev"] # "" indicates the core API group
  resources: ["tasks"]
  verbs: ["get"]
...
