---
apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
  name: cicd
  namespace: default
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/tags: docker, build-image, push-image, dind
    tekton.dev/displayName: docker-build
spec:
  description: >-
    This task will build and push an image using docker.
    The task will build an out image out of a Dockerfile.
    This image will be pushed to an image registry.
    The image will be built and pushed using a dind sidecar over TCP+TLS.
  params:
  - name: image
    description: Reference of the image docker will produce.
  - name: builder_image
    description: The location of the docker builder image.
    default: docker
  - name: dockerfile
    description: Path to the Dockerfile to build.
    default: ./Dockerfile
  - name: context
    description: Path to the directory to use as context.
    default: .
  - name: build_extra_args
    description: Extra parameters passed for the build command when building images.
    default: ""
  - name: push_extra_args
    description: Extra parameters passed for the push command when pushing images.
    default: ""
  - name: insecure_registry
    description: Allows the user to push to an insecure registry that has been specified
    default: ""
  workspaces:
  - name: source
  results:
  - name: IMAGE_DIGEST
    description: Digest of the image just built.
  steps:
  - name: initialize-helm
    image: $(params.image)
    script: |
      /usr/local/bin/00-init.sh
    workingDir: $(workspaces.source.path)
  - name: lint-package-chart
    image: $(params.image)
    script: |
      /usr/local/bin/01-ci.sh
    workingDir: $(workspaces.source.path)
  - name: deploy
    image: $(params.image)
    script: |
      /usr/local/bin/02-cd.sh
    workingDir: $(workspaces.source.path)
...
