---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: prun-create-scdi
spec:
  pipelineRef:
    name: p-create-scdi
  workspaces:
  - name: shared-workspace
    persistentvolumeclaim:
      claimName: docker-source-pvc
  params:
  - name: git-url
    value: "https://github.com/slfletch/mvp"
  - name: subdirectory
    value: ""
  - name: git-revision
    value: "master"
  - name: deleteExisting
    value: "true"
  - name: httpProxy
    value: ""
  - name: httpsProxy
    value: ""
  - name: noProxy
    value: ""
  - name: image
    value: benld.localdomain:30003/nrf/scdi:1.1
  - name: dockerfile
    value: ./tenant1/Dockerfile
  - name: insecure_registry
    value: "benld.localdomain:30003/nrf"
...
