---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: docker-test-pipeline
spec:
  workspaces:
  - name: shared-workspace
  tasks:
  - name: fetch-repository
    taskRef:
      name: git-clone
    workspaces:
    - name: output
      workspace: shared-workspace
    params:
    - name: url
      value: https://github.com/slfletch/mvp
    - name: subdirectory
      value: ""
    - name: deleteExisting
      value: "true"
  - name: docker-build
    taskRef:
      name: docker-build
    runAfter:
    - fetch-repository
    workspaces:
    - name: source
      workspace: shared-workspace
    params:
    - name: image
      value: stacey-0.localdomain:30003/tcicd/scdi:1.0
    - name: insecure_registry
      value: registry.docker-build-0-1.svc.cluster.local:5000
    - name: dockerfile
      value: ./tenant1/Dockerfile
...