---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: docker-test-pipeline-run
spec:
  pipelineRef:
    name: docker-test-pipeline
  workspaces:
  - name: shared-workspace
    persistentvolumeclaim:
      claimName: docker-source-pvc