apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: demo-task-run-scdi-valid-user
  namespace: demo
spec:
  serviceAccountName: demo-svc
  taskSpec:
    steps:
    - name: demo-setup-valid-user
      image: mtn52r08c001.mini.mtn52c.cci.att.com:30003/tenent0/scdi:1.1
      script: |
        #!/bin/bash
        /usr/local/bin/setup.sh
    - name: demo-run-valid-user
      image: mtn52r08c001.mini.mtn52c.cci.att.com:30003/tenent0/scdi:1.1
      script: |
        #!/bin/bas
        /usr/local/bin/run.sh
    - name: demo-test-valid-user
      image: stacey-0.localdomain:30003/tcicd/demo:1.5
      script: |
        #!/bin/bash
        /usr/local/bin/test.sh
