---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: pr-create-rbac
spec:
  pipelineRef:
    name: p-run-kubectl-command
  workspaces:
  - name: shared-data
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
        storageClassName: nfs-provisioner
  params:
  - name: repo-url
    value: <gerrit-url>
  - name: branch-name
    value: <gerrit-branch-name>
  - name: set-namespace
    value: <namespace>
  - name: httpProxy
    value: <http-proxy>
  - name: httpsProxy
    value: <https-proxy>
  - name: noProxy
    value: <no-proxy>
  - name: kubectlCommand
    value: "cat $(workspaces.source.path)/cluster-admin/rdmSite/$(params.rbac-ns)/rbac/rbac.yaml | kubectl apply -f -"
...
