---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: pr-create-secrets
spec:
  pipelineRef:
    name: p-run-kubectl-command
  workspaces:
  - name: shared-data
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
        storageClassName: nfs-provisioner
  params:
  - name: repo-url
    value: <gerrit-url>
  - name: branch-name
    value: <gerrit-branch-name>
  - name: set-namespace
    value: <namespace>
  - name: httpProxy
    value: <http-proxy>
  - name: httpsProxy
    value: <https-proxy>
  - name: noProxy
    value: <no-proxy>
  - name: harbor-user
    value: <harbor-user>
  - name: harbor-password
    value: <harbor-password>
  - name: kubectlCommand
    value: "kubectl create secret -n $(params.set-namespace) docker-registry --docker-password $(params.harbor-password) --docker-username $(harbor-user) --docker-server mtn52r08c001.mini.mtn52c.cci.att.com:30003 harbor-registry-creds"
...
