---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: p-run-kubectl-command
spec:
  description: |
    Add service account that will have access to k8s objects
  params:
  - name: repo-url
  - name: branch-name
  - name: set-namespace
  - name: httpProxy
  - name: httpsProxy
  - name: noProxy
  - name: kubectlCommand
  workspaces:
  - name: shared-data
    description: |
      This workspace will receive the cloned git repo and be passed
      to the next Task for the repo's README.md file to be read.
  tasks:
  - name: fetch-repo
    taskRef:
      name: git-clone
    workspaces:
    - name: output
      workspace: shared-data
    params:
    - name: url
      value: $(params.repo-url)
    - name: revision
      value: $(params.branch-name)
    - name: httpProxy
      value: $(params.httpProxy)
    - name: httpsProxy
      value: $(params.httpsProxy)
    - name: noProxy
      value: $(params.noProxy)
  - name: run-kubectl-command
    runAfter: ["fetch-repo"]  # Wait until the clone is done before reading the readme.
    workspaces:
    - name: source
      workspace: shared-data
    params:
    - name: set-namespace
      value: $(params.set-namespace)
    - name: kubectlCommand
      value: $(params.kubectlCommand)
    taskSpec:
      workspaces:
      - name: source
      params:
      - name: set-namespace
      - name: kubectlCommand
      steps:
      - image: lachlanevenson/k8s-kubectl
        script: |
          $(params.kubectlCommand)
...
