apiVersion: v1
kind: ServiceAccount
metadata:
  name: cnf-b-svc
  namespace: cnf-b
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mvp-role
  namespace: cnf-b
rules:
- apiGroups: ["helm.fluxcd.io"] # "" indicates the core API group
  resources: ["helmreleases"]
  verbs: ["get","list","describe"]
- apiGroups: [""] # "" indicates the core API group
  resources: ["secrets"]
  verbs: ["get","list"]
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "watch", "list","describe"]
- apiGroups: ["cnf-b"] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["create", "delete", "list","describe"]
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - list
  - watch
- apiGroups:
  - ""
  resourceNames:
  - config-logging
  - config-observability
  - config-leader-election
  resources:
  - configmaps
  verbs:
  - get
...
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mvp-rolebinding
  namespace: cnf-b
subjects:
# Kubernetes service account
- kind: ServiceAccount
  name: cnf-b-svc
roleRef:
  kind: Role
  name: mvp-role
  apiGroup: ""
...
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mvp-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: mvp-svc
    namespace: cnf-b
...
