apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: remote-ssh-secret
data:
  passphrase: passphrase of the private ssh key in base64
  privatekey: your private ssh key in base64
  password: password (if used to login the remote server)
  fingerprint: |
    fingerprint SHA256 of the host public key. Default is to skip verification
  ciphers: |
    The allowed cipher algorithms. If unspecified then a sensible
