apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: p-add-rbac
spec:
  description: |
    Add service account that will have access to k8s objects
  params:
  - name: repo-url
    type: string
    description: The git repository URL to clone from.
  - name: branch-name
    type: string
    description: The git branch to clone.
  workspaces:
  - name: shared-data
    description: |
      This workspace will receive the cloned git repo and be passed
      to the next Task for the repo's README.md file to be read.
  tasks:
  - name: fetch-repo
    taskRef:
      name: git-clone
    workspaces:
    - name: output
      workspace: shared-data
    params:
    - name: url
      value: $(params.repo-url)
    - name: revision
      value: $(params.branch-name)
  - name: create-rbac
    runAfter: ["fetch-repo"]  # Wait until the clone is done before reading the readme.
    workspaces:
    - name: source
      workspace: shared-data
    taskSpec:
      workspaces:
      - name: source
      steps:
      - image: lachlanevenson/k8s-kubectl
        script: |
          kubectl apply -f $(workspaces.source.path)/service_accounts/svc-account.yaml
          kubectl apply -f $(workspaces.source.path)/roles/mvp-role.yaml
          kubectl apply -f $(workspaces.source.path)/rolebindings/mvp-rolebindings.yaml
          kubectl apply -f $(workspaces.source.path)/clusterrolebindings/mvp-clusterrolebinding.yaml
---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: git-clone-checking-out-a-branch
spec:
  pipelineRef:
    name: p-add-rbac
  workspaces:
  - name: shared-data
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
        storageClassName: nfs-provisioner
  params:
  - name: repo-url
    value: https://github.com/slfletch/mvp.git
  - name: branch-name
    value: master
